"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const adminController_1 = require("../controllers/adminController");
const auth_1 = require("../middlewares/auth");
const router = (0, express_1.Router)();
router.get('/stats', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getAdminStats);
router.get('/users', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getAllUsers);
router.get('/hostels', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getAllHostels);
router.put('/hostels/:id/approve', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.approveHostel);
router.put('/hostels/:id/reject', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.rejectHostel);
router.get('/settlements', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getAllSettlements);
router.put('/hostels/:hostelId/verify', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.verifyHostel);
router.get('/bookings', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getBookings);
router.get('/analytics', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getAnalytics);
router.get('/commission', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.getCommissionSettings);
router.put('/commission', auth_1.authenticate, (0, auth_1.authorize)(['admin']), adminController_1.updateCommissionSettings);
exports.default = router;
