"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const analyticsController_1 = require("../controllers/analyticsController");
const adminController_1 = require("../controllers/adminController");
const auth_1 = require("../middlewares/auth");
const router = (0, express_1.Router)();
router.post('/events', analyticsController_1.trackEvent);
router.post('/owner/response', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), analyticsController_1.trackOwnerResponse);
router.get('/dashboard', auth_1.authenticate, (0, auth_1.authorize)(['admin']), analyticsController_1.getDashboardAnalytics);
router.get('/owner', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), analyticsController_1.getOwnerAnalytics);
router.get('/owner/dashboard', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), analyticsController_1.getOwnerAnalytics);
router.get('/owner/dashboard-stats', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.getOwnerDashboardStats);
router.get('/owner/bookings', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.getOwnerBookings);
router.get('/owner/analytics', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), analyticsController_1.getOwnerAnalytics);
router.put('/owner/bookings/:bookingId', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.updateBookingStatus);
router.get('/owner/:ownerId/analytics', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.getOwnerAnalytics);
router.get('/owner/:ownerId/bookings', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.getOwnerBookings);
router.put('/owner/bookings/:bookingId', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.updateBookingStatus);
router.get('/owner/:ownerId/properties', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.getOwnerProperties);
router.put('/owner/properties/:propertyId/pricing', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner']), adminController_1.updateRoomPricing);
exports.default = router;
