"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const hostelController_1 = require("../controllers/hostelController");
const auth_1 = require("../middlewares/auth");
const router = (0, express_1.Router)();
router.post('/', auth_1.authenticate, (0, auth_1.authorize)(['hostel_owner', 'admin']), hostelController_1.createHostel);
router.get('/', hostelController_1.getHostels);
router.get('/owner', auth_1.authenticate, hostelController_1.getOwnerHostels);
router.get('/:id', hostelController_1.getHostelById);
router.put('/:id', auth_1.authenticate, hostelController_1.updateHostel);
router.put('/:hostelId/rooms/:roomId/price', auth_1.authenticate, hostelController_1.updateRoomPrice);
exports.default = router;
